check for success and failure; send slack message

diff --git a/.github/workflows/check-test-runs.yml b/.github/workflows/check-test-runs.yml
--- a/.github/workflows/check-test-runs.yml
+++ b/.github/workflows/check-test-runs.yml
@@ -87,6 +87,42 @@ jobs:
     - name: "Extract apex test results"
       run: |
         sf apex get test -i ${{env.UAT_TEST_RUN_ID}}
+        if [ $? -eq 0 ]; then
+          echo "TEST_RESULT=FAIL" >> $GITHUB_ENV
+        else
+          echo "TEST_RESULT=PASS" >> $GITHUB_ENV
+        fi
+        
+  send_slack_message:
+    runs-on: ubuntu-latest
+    needs: [check_tests_integration_org,check_tests_UAT_org]
+    steps:
+      - name: Post to a Slack channel
+        id: slack
+        uses: slackapi/slack-github-action@v1.24.0
+        with:
+          # Slack channel id, channel name, or user id to post message.
+          # See also: https://api.slack.com/methods/chat.postMessage#channels
+          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
+          channel-id: 'C062G1V3KKK'
+          # For posting a simple plain text message
+          payload: |
+            {
+              "text": "Test Runs Finished",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Finishing running tests"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+      
+
         
    
     
